# Encryption key for cookie session. It is recommended to use key with 32 or 64 bytes.
# New sessions will be saved using the first key. Multiple keys can be provided to allow for key rotation.
# If you don't set any it will be dynamic and will not persist proxy restarts (users will need to re-login).
# This is a list, please preserve "-" with each row.
cookie_session_secrets:
  # - your-own-cookie-secret

# User credentials as obtained from the registration.
# This is a dict, please put an indentation with each row.
user_credentials:
  # email1@example.com: encodeeeed-secret-data1
  # email2@example.com: encodeeeed-secret-data2
